/**
 * country-codes.ts — Catálogo COMPLETO de indicativos telefónicos por país
 * (nombre en español + ISO2 + prefijo). Ordenado alfabéticamente.
 *
 * Fuente única para los selectores de celular (Agregar/Editar Beneficiario,
 * Crear Contrato, Migrar Contrato). Los `<select>` nativos permiten typeahead:
 * el operador teclea el nombre del país y salta a él.
 */
export interface CountryCode {
  pais: string;   // nombre en español
  codigo: string; // ISO 3166-1 alpha-2
  prefijo: string; // indicativo internacional
}

export const COUNTRY_CODES: CountryCode[] = [
  { pais: 'Afganistán', codigo: 'AF', prefijo: '+93' },
  { pais: 'Albania', codigo: 'AL', prefijo: '+355' },
  { pais: 'Alemania', codigo: 'DE', prefijo: '+49' },
  { pais: 'Andorra', codigo: 'AD', prefijo: '+376' },
  { pais: 'Angola', codigo: 'AO', prefijo: '+244' },
  { pais: 'Anguila', codigo: 'AI', prefijo: '+1264' },
  { pais: 'Antigua y Barbuda', codigo: 'AG', prefijo: '+1268' },
  { pais: 'Arabia Saudita', codigo: 'SA', prefijo: '+966' },
  { pais: 'Argelia', codigo: 'DZ', prefijo: '+213' },
  { pais: 'Argentina', codigo: 'AR', prefijo: '+54' },
  { pais: 'Armenia', codigo: 'AM', prefijo: '+374' },
  { pais: 'Aruba', codigo: 'AW', prefijo: '+297' },
  { pais: 'Australia', codigo: 'AU', prefijo: '+61' },
  { pais: 'Austria', codigo: 'AT', prefijo: '+43' },
  { pais: 'Azerbaiyán', codigo: 'AZ', prefijo: '+994' },
  { pais: 'Bahamas', codigo: 'BS', prefijo: '+1242' },
  { pais: 'Bangladés', codigo: 'BD', prefijo: '+880' },
  { pais: 'Barbados', codigo: 'BB', prefijo: '+1246' },
  { pais: 'Baréin', codigo: 'BH', prefijo: '+973' },
  { pais: 'Bélgica', codigo: 'BE', prefijo: '+32' },
  { pais: 'Belice', codigo: 'BZ', prefijo: '+501' },
  { pais: 'Benín', codigo: 'BJ', prefijo: '+229' },
  { pais: 'Bermudas', codigo: 'BM', prefijo: '+1441' },
  { pais: 'Bielorrusia', codigo: 'BY', prefijo: '+375' },
  { pais: 'Bolivia', codigo: 'BO', prefijo: '+591' },
  { pais: 'Bosnia y Herzegovina', codigo: 'BA', prefijo: '+387' },
  { pais: 'Botsuana', codigo: 'BW', prefijo: '+267' },
  { pais: 'Brasil', codigo: 'BR', prefijo: '+55' },
  { pais: 'Brunéi', codigo: 'BN', prefijo: '+673' },
  { pais: 'Bulgaria', codigo: 'BG', prefijo: '+359' },
  { pais: 'Burkina Faso', codigo: 'BF', prefijo: '+226' },
  { pais: 'Burundi', codigo: 'BI', prefijo: '+257' },
  { pais: 'Bután', codigo: 'BT', prefijo: '+975' },
  { pais: 'Cabo Verde', codigo: 'CV', prefijo: '+238' },
  { pais: 'Camboya', codigo: 'KH', prefijo: '+855' },
  { pais: 'Camerún', codigo: 'CM', prefijo: '+237' },
  { pais: 'Canadá', codigo: 'CA', prefijo: '+1' },
  { pais: 'Catar', codigo: 'QA', prefijo: '+974' },
  { pais: 'Chad', codigo: 'TD', prefijo: '+235' },
  { pais: 'Chile', codigo: 'CL', prefijo: '+56' },
  { pais: 'China', codigo: 'CN', prefijo: '+86' },
  { pais: 'Chipre', codigo: 'CY', prefijo: '+357' },
  { pais: 'Colombia', codigo: 'CO', prefijo: '+57' },
  { pais: 'Comoras', codigo: 'KM', prefijo: '+269' },
  { pais: 'Congo', codigo: 'CG', prefijo: '+242' },
  { pais: 'Congo (RD)', codigo: 'CD', prefijo: '+243' },
  { pais: 'Corea del Norte', codigo: 'KP', prefijo: '+850' },
  { pais: 'Corea del Sur', codigo: 'KR', prefijo: '+82' },
  { pais: 'Costa de Marfil', codigo: 'CI', prefijo: '+225' },
  { pais: 'Costa Rica', codigo: 'CR', prefijo: '+506' },
  { pais: 'Croacia', codigo: 'HR', prefijo: '+385' },
  { pais: 'Cuba', codigo: 'CU', prefijo: '+53' },
  { pais: 'Curazao', codigo: 'CW', prefijo: '+599' },
  { pais: 'Dinamarca', codigo: 'DK', prefijo: '+45' },
  { pais: 'Dominica', codigo: 'DM', prefijo: '+1767' },
  { pais: 'Ecuador', codigo: 'EC', prefijo: '+593' },
  { pais: 'Egipto', codigo: 'EG', prefijo: '+20' },
  { pais: 'El Salvador', codigo: 'SV', prefijo: '+503' },
  { pais: 'Emiratos Árabes Unidos', codigo: 'AE', prefijo: '+971' },
  { pais: 'Eritrea', codigo: 'ER', prefijo: '+291' },
  { pais: 'Eslovaquia', codigo: 'SK', prefijo: '+421' },
  { pais: 'Eslovenia', codigo: 'SI', prefijo: '+386' },
  { pais: 'España', codigo: 'ES', prefijo: '+34' },
  { pais: 'Estados Unidos', codigo: 'US', prefijo: '+1' },
  { pais: 'Estonia', codigo: 'EE', prefijo: '+372' },
  { pais: 'Etiopía', codigo: 'ET', prefijo: '+251' },
  { pais: 'Filipinas', codigo: 'PH', prefijo: '+63' },
  { pais: 'Finlandia', codigo: 'FI', prefijo: '+358' },
  { pais: 'Fiyi', codigo: 'FJ', prefijo: '+679' },
  { pais: 'Francia', codigo: 'FR', prefijo: '+33' },
  { pais: 'Gabón', codigo: 'GA', prefijo: '+241' },
  { pais: 'Gambia', codigo: 'GM', prefijo: '+220' },
  { pais: 'Georgia', codigo: 'GE', prefijo: '+995' },
  { pais: 'Ghana', codigo: 'GH', prefijo: '+233' },
  { pais: 'Gibraltar', codigo: 'GI', prefijo: '+350' },
  { pais: 'Granada', codigo: 'GD', prefijo: '+1473' },
  { pais: 'Grecia', codigo: 'GR', prefijo: '+30' },
  { pais: 'Groenlandia', codigo: 'GL', prefijo: '+299' },
  { pais: 'Guadalupe', codigo: 'GP', prefijo: '+590' },
  { pais: 'Guam', codigo: 'GU', prefijo: '+1671' },
  { pais: 'Guatemala', codigo: 'GT', prefijo: '+502' },
  { pais: 'Guayana Francesa', codigo: 'GF', prefijo: '+594' },
  { pais: 'Guinea', codigo: 'GN', prefijo: '+224' },
  { pais: 'Guinea Ecuatorial', codigo: 'GQ', prefijo: '+240' },
  { pais: 'Guinea-Bisáu', codigo: 'GW', prefijo: '+245' },
  { pais: 'Guyana', codigo: 'GY', prefijo: '+592' },
  { pais: 'Haití', codigo: 'HT', prefijo: '+509' },
  { pais: 'Honduras', codigo: 'HN', prefijo: '+504' },
  { pais: 'Hong Kong', codigo: 'HK', prefijo: '+852' },
  { pais: 'Hungría', codigo: 'HU', prefijo: '+36' },
  { pais: 'India', codigo: 'IN', prefijo: '+91' },
  { pais: 'Indonesia', codigo: 'ID', prefijo: '+62' },
  { pais: 'Irak', codigo: 'IQ', prefijo: '+964' },
  { pais: 'Irán', codigo: 'IR', prefijo: '+98' },
  { pais: 'Irlanda', codigo: 'IE', prefijo: '+353' },
  { pais: 'Islandia', codigo: 'IS', prefijo: '+354' },
  { pais: 'Islas Caimán', codigo: 'KY', prefijo: '+1345' },
  { pais: 'Islas Vírgenes Británicas', codigo: 'VG', prefijo: '+1284' },
  { pais: 'Islas Vírgenes de EE. UU.', codigo: 'VI', prefijo: '+1340' },
  { pais: 'Israel', codigo: 'IL', prefijo: '+972' },
  { pais: 'Italia', codigo: 'IT', prefijo: '+39' },
  { pais: 'Jamaica', codigo: 'JM', prefijo: '+1876' },
  { pais: 'Japón', codigo: 'JP', prefijo: '+81' },
  { pais: 'Jordania', codigo: 'JO', prefijo: '+962' },
  { pais: 'Kazajistán', codigo: 'KZ', prefijo: '+7' },
  { pais: 'Kenia', codigo: 'KE', prefijo: '+254' },
  { pais: 'Kirguistán', codigo: 'KG', prefijo: '+996' },
  { pais: 'Kiribati', codigo: 'KI', prefijo: '+686' },
  { pais: 'Kuwait', codigo: 'KW', prefijo: '+965' },
  { pais: 'Laos', codigo: 'LA', prefijo: '+856' },
  { pais: 'Lesoto', codigo: 'LS', prefijo: '+266' },
  { pais: 'Letonia', codigo: 'LV', prefijo: '+371' },
  { pais: 'Líbano', codigo: 'LB', prefijo: '+961' },
  { pais: 'Liberia', codigo: 'LR', prefijo: '+231' },
  { pais: 'Libia', codigo: 'LY', prefijo: '+218' },
  { pais: 'Liechtenstein', codigo: 'LI', prefijo: '+423' },
  { pais: 'Lituania', codigo: 'LT', prefijo: '+370' },
  { pais: 'Luxemburgo', codigo: 'LU', prefijo: '+352' },
  { pais: 'Macao', codigo: 'MO', prefijo: '+853' },
  { pais: 'Macedonia del Norte', codigo: 'MK', prefijo: '+389' },
  { pais: 'Madagascar', codigo: 'MG', prefijo: '+261' },
  { pais: 'Malasia', codigo: 'MY', prefijo: '+60' },
  { pais: 'Malaui', codigo: 'MW', prefijo: '+265' },
  { pais: 'Maldivas', codigo: 'MV', prefijo: '+960' },
  { pais: 'Malí', codigo: 'ML', prefijo: '+223' },
  { pais: 'Malta', codigo: 'MT', prefijo: '+356' },
  { pais: 'Marruecos', codigo: 'MA', prefijo: '+212' },
  { pais: 'Martinica', codigo: 'MQ', prefijo: '+596' },
  { pais: 'Mauricio', codigo: 'MU', prefijo: '+230' },
  { pais: 'Mauritania', codigo: 'MR', prefijo: '+222' },
  { pais: 'México', codigo: 'MX', prefijo: '+52' },
  { pais: 'Micronesia', codigo: 'FM', prefijo: '+691' },
  { pais: 'Moldavia', codigo: 'MD', prefijo: '+373' },
  { pais: 'Mónaco', codigo: 'MC', prefijo: '+377' },
  { pais: 'Mongolia', codigo: 'MN', prefijo: '+976' },
  { pais: 'Montenegro', codigo: 'ME', prefijo: '+382' },
  { pais: 'Mozambique', codigo: 'MZ', prefijo: '+258' },
  { pais: 'Namibia', codigo: 'NA', prefijo: '+264' },
  { pais: 'Nauru', codigo: 'NR', prefijo: '+674' },
  { pais: 'Nepal', codigo: 'NP', prefijo: '+977' },
  { pais: 'Nicaragua', codigo: 'NI', prefijo: '+505' },
  { pais: 'Níger', codigo: 'NE', prefijo: '+227' },
  { pais: 'Nigeria', codigo: 'NG', prefijo: '+234' },
  { pais: 'Noruega', codigo: 'NO', prefijo: '+47' },
  { pais: 'Nueva Zelanda', codigo: 'NZ', prefijo: '+64' },
  { pais: 'Omán', codigo: 'OM', prefijo: '+968' },
  { pais: 'Países Bajos', codigo: 'NL', prefijo: '+31' },
  { pais: 'Pakistán', codigo: 'PK', prefijo: '+92' },
  { pais: 'Palaos', codigo: 'PW', prefijo: '+680' },
  { pais: 'Palestina', codigo: 'PS', prefijo: '+970' },
  { pais: 'Panamá', codigo: 'PA', prefijo: '+507' },
  { pais: 'Papúa Nueva Guinea', codigo: 'PG', prefijo: '+675' },
  { pais: 'Paraguay', codigo: 'PY', prefijo: '+595' },
  { pais: 'Perú', codigo: 'PE', prefijo: '+51' },
  { pais: 'Polinesia Francesa', codigo: 'PF', prefijo: '+689' },
  { pais: 'Polonia', codigo: 'PL', prefijo: '+48' },
  { pais: 'Portugal', codigo: 'PT', prefijo: '+351' },
  { pais: 'Puerto Rico', codigo: 'PR', prefijo: '+1787' },
  { pais: 'Reino Unido', codigo: 'GB', prefijo: '+44' },
  { pais: 'República Centroafricana', codigo: 'CF', prefijo: '+236' },
  { pais: 'República Checa', codigo: 'CZ', prefijo: '+420' },
  { pais: 'República Dominicana', codigo: 'DO', prefijo: '+1809' },
  { pais: 'Ruanda', codigo: 'RW', prefijo: '+250' },
  { pais: 'Rumania', codigo: 'RO', prefijo: '+40' },
  { pais: 'Rusia', codigo: 'RU', prefijo: '+7' },
  { pais: 'Sahara Occidental', codigo: 'EH', prefijo: '+212' },
  { pais: 'Samoa', codigo: 'WS', prefijo: '+685' },
  { pais: 'San Cristóbal y Nieves', codigo: 'KN', prefijo: '+1869' },
  { pais: 'San Marino', codigo: 'SM', prefijo: '+378' },
  { pais: 'San Vicente y las Granadinas', codigo: 'VC', prefijo: '+1784' },
  { pais: 'Santa Lucía', codigo: 'LC', prefijo: '+1758' },
  { pais: 'Santo Tomé y Príncipe', codigo: 'ST', prefijo: '+239' },
  { pais: 'Senegal', codigo: 'SN', prefijo: '+221' },
  { pais: 'Serbia', codigo: 'RS', prefijo: '+381' },
  { pais: 'Seychelles', codigo: 'SC', prefijo: '+248' },
  { pais: 'Sierra Leona', codigo: 'SL', prefijo: '+232' },
  { pais: 'Singapur', codigo: 'SG', prefijo: '+65' },
  { pais: 'Siria', codigo: 'SY', prefijo: '+963' },
  { pais: 'Somalia', codigo: 'SO', prefijo: '+252' },
  { pais: 'Sri Lanka', codigo: 'LK', prefijo: '+94' },
  { pais: 'Suazilandia (Esuatini)', codigo: 'SZ', prefijo: '+268' },
  { pais: 'Sudáfrica', codigo: 'ZA', prefijo: '+27' },
  { pais: 'Sudán', codigo: 'SD', prefijo: '+249' },
  { pais: 'Sudán del Sur', codigo: 'SS', prefijo: '+211' },
  { pais: 'Suecia', codigo: 'SE', prefijo: '+46' },
  { pais: 'Suiza', codigo: 'CH', prefijo: '+41' },
  { pais: 'Surinam', codigo: 'SR', prefijo: '+597' },
  { pais: 'Tailandia', codigo: 'TH', prefijo: '+66' },
  { pais: 'Taiwán', codigo: 'TW', prefijo: '+886' },
  { pais: 'Tanzania', codigo: 'TZ', prefijo: '+255' },
  { pais: 'Tayikistán', codigo: 'TJ', prefijo: '+992' },
  { pais: 'Timor Oriental', codigo: 'TL', prefijo: '+670' },
  { pais: 'Togo', codigo: 'TG', prefijo: '+228' },
  { pais: 'Tonga', codigo: 'TO', prefijo: '+676' },
  { pais: 'Trinidad y Tobago', codigo: 'TT', prefijo: '+1868' },
  { pais: 'Túnez', codigo: 'TN', prefijo: '+216' },
  { pais: 'Turkmenistán', codigo: 'TM', prefijo: '+993' },
  { pais: 'Turquía', codigo: 'TR', prefijo: '+90' },
  { pais: 'Tuvalu', codigo: 'TV', prefijo: '+688' },
  { pais: 'Ucrania', codigo: 'UA', prefijo: '+380' },
  { pais: 'Uganda', codigo: 'UG', prefijo: '+256' },
  { pais: 'Uruguay', codigo: 'UY', prefijo: '+598' },
  { pais: 'Uzbekistán', codigo: 'UZ', prefijo: '+998' },
  { pais: 'Vanuatu', codigo: 'VU', prefijo: '+678' },
  { pais: 'Venezuela', codigo: 'VE', prefijo: '+58' },
  { pais: 'Vietnam', codigo: 'VN', prefijo: '+84' },
  { pais: 'Yemen', codigo: 'YE', prefijo: '+967' },
  { pais: 'Yibuti', codigo: 'DJ', prefijo: '+253' },
  { pais: 'Zambia', codigo: 'ZM', prefijo: '+260' },
  { pais: 'Zimbabue', codigo: 'ZW', prefijo: '+263' },
];
